NON_GAMBLING_SITES = [
    # 🇮🇩 E-Commerce (25)
    "https://www.bhinneka.com",
    "https://www.bukalapak.com",
    "https://www.orami.co.id",
    "https://www.ralali.com",
    "https://doss.co.id",
    "https://crewdible.com",
    "https://www.hitoko.co.id",
    "https://www.bigseller.com",
    "https://www.oyindonesia.com",
    "https://www.mbizmarket.co.id",
    "https://www.sepatu.com",
    "https://www.eigeradventure.com",
    "https://id.yamaha.com",
    # manual screenshot --
    # "https://www.jakmall.com",
    # "https://www.lazada.co.id",
    # "https://www.indotrading.com",
    # "https://iprice.co.id",
    # "https://www.tokopedia.com",
    # "https://www.shopee.co.id",
    # "https://www.blibli.com",
    # "https://www.jamtangan.com",
    # "https://www.zalora.co.id",
    # "https://www.olx.co.id",
    # "https://www.dhl.com",
    # "https://www.sociolla.com"
    # 🌎 Global E-Commerce (25)
    "https://www.ebay.com",
    "https://www.lightinthebox.com",
    "https://www.walmart.com",
    "https://www.houzz.com",
    "https://www.cdiscount.com",
    "https://sell.amazon.com",
    "https://www.vinted.com",
    "https://thegadgetflow.com",
    "https://www.verizon.com",
    # manual screenshot --
    # "https://www.aptdeco.com",
    # "https://acquire.com",
    # "https://flippa.com",
    # "https://www.whatnot.com",
    # "https://www.depop.com",
    # "https://www.thredup.com",
    # "https://www.bizbuysell.com",
    # "https://gameflip.com",
    # "https://www.macys.com",
    # "https://www.qvc.com",
    # "https://www.jcrew.com",
    # "https://senseng-apparel.com",
    # "https://www.bestbuy.com",
    # "https://www.asos.com",
    # "https://www.ecwid.com",
    # "https://www.kimstore.com"
    # 📰 Media & News (Indonesia) (20)
    "https://www.antaranews.com",
    "https://www.detik.com",
    "https://infopublik.id",
    "https://kumparan.com",
    "https://theconversation.com",
    "https://www.beritajakarta.id",
    "https://news.ddtc.co.id",
    "https://olnewsindonesia.com",
    "https://www.lensaindonesia.com",
    # manual screenshot --
    # "https://www.liputan6.com",
    # "https://www.dw.com/id",
    # "https://indo1.id",
    # "https://www.bbc.com/indonesia",
    # "https://www.tempo.co",
    # "https://www.kompas.com",
    # "https://www.sindonews.com",
    # "https://www.okezone.com",
    # "https://www.thejakartapost.com",
    # "https://batu.times.co.id",
    # "https://beritaindonesia.id"
    # 🌍 Media & News (Global) (20)
    # manual screenshot --
    # "https://ktla.com",
    # "https://www.latimes.com",
    # "https://www.washingtonpost.com",
    # "https://www.foxnews.com",
    # "https://www.dailynews.com",
    # "https://www.aljazeera.com",
    # "https://news.yahoo.com",
    # "https://www.pbs.org",
    # "https://www.nbcmiami.com",
    # "https://apnews.com",
    # "https://abcnews.go.com",
    # "https://www.npr.org",
    # "https://www.cbsnews.com",
    # "https://abc7.com",
    # "https://www.foxla.com"
    # "https://www.goerie.com"
    # "https://www.nbclosangeles.com",
    # "https://www.reuters.com",
    # "https://www.politico.com",
    # "https://www.theguardian.com/us",
    # 📚 Edukasi (Global & Indonesia) (30)
    # manual screenshot --
    # "https://www.utah.edu",
    # "https://www.ufl.edu",
    # "https://www.csusm.edu",
    # "https://umd.edu",
    # "https://www.arizona.edu",
    # "https://www.ucla.edu",
    # "https://uci.edu",
    # "https://www.ucr.edu",
    # "https://www.chapman.edu",
    # "https://www.ucsb.edu",
    # "https://usla.edu",
    # "https://laverne.edu",
    # "https://www.universityofcalifornia.edu",
    # "https://www.redlands.edu",
    # "https://www.fullerton.edu",
    # "https://www.harvard.edu",
    # "https://bandunguniversity.ac.id",
    # "https://www.unpad.ac.id",
    # "https://www.maranatha.edu",
    # "https://www.unas.ac.id",
    # "https://univpancasila.ac.id",
    # "https://www.ub.ac.id/id",
    # "https://www.unand.ac.id",
    # "https://www.unila.ac.id",
    # "https://universitaspertamina.ac.id",
    # "https://www.umn.ac.id",
    # "https://www.unklab.ac.id",
    # "https://um.ac.id",
    # "https://bunghatta.ac.id",
    # "https://www.budiluhur.ac.id",
    # "https://unpar.ac.id",
    # "https://www.unpas.ac.id",
    # "https://www.ubaya.ac.id",
    # 🏛️ Pemerintahan / Organisasi Resmi (25)
    # manual screenshot --
    # "https://kemnaker.go.id",
    # "https://www.menpan.go.id",
    # "https://www.kemenkeu.go.id",
    # "https://kemenag.go.id",
    # "https://www.pertanian.go.id",
    # "https://www.setneg.go.id",
    # "https://setkab.go.id",
    # "https://www.komdigi.go.id",
    # "https://banhub.kepriprov.go.id",
    # "https://www.kemenperin.go.id",
    # "https://kemendikdasmen.go.id",
    # "https://www.ekon.go.id",
    # "https://www.esdm.go.id",
    # "https://www.kemhan.go.id",
    # "https://pemberdayaan.go.id",
    # "https://kemdiktisaintek.go.id",
    # "https://pkp.go.id",
    # "https://kemenpora.go.id",
    # "https://dephub.go.id",
    # "https://umkm.go.id",
    # "https://kemensos.go.id",
    # "https://kemlu.go.id",
    # "https://www.atrbpn.go.id",
    # "https://kemenimipas.go.id",
    # "https://kemenpppa.go.id",
    # 💰 Finansial (20)
    # manual screenshot --
    # "https://www.ocbc.com",
    # "https://www.uob.com.sg",
    # "https://www.citibank.com",
    # "https://www.hsbc.com.sg",
    # "https://www.manulife.com.sg",
    # "https://www.standardchartered.com",
    # "https://www.moneygram.com",
    # "https://www.paypal.com",
    # "https://www.americanexpress.com",
    # "https://www.mastercard.com",
    # "https://www.visa.com",
    # "https://www.bca.co.id",
    # "https://www.bri.co.id",
    # "https://www.cimbniaga.co.id",
    # "https://www.bankmandiri.co.id",
    # "https://www.jenius.com",
    # "https://www.danamon.co.id"
    # "https://www.bni.co.id",
    # "https://www.bankmega.com",
    # "https://www.bankjatim.co.id",
    # 🎬 Hiburan / Streaming (15)
    # manual screenshot --
    # "https://www.hulu.com",
    # "https://www.disneyplus.com",
    # "https://www.paramountplus.com",
    # "https://www.crunchyroll.com",
    # "https://www.soundcloud.com",
    # "https://www.netflix.com",
    # "https://www.visionplus.id",
    # "https://klikfilm.com",
    # "https://www.vidio.com",
    # "https://www.iqiyi.com",
    # "https://www.spotify.com",
    # "https://www.youtube.com",
    # "https://www.joox.com",
    # "https://www.hbomax.com",
    # "https://open.noice.id",
    # 💼 SaaS / Tools (20)
    # manual screenshot --
    # "https://www.canva.com",
    # "https://www.figma.com",
    # "https://www.notion.so",
    # "https://www.slack.com",
    # "https://www.asana.com",
    # "https://www.adobe.com",
    # "https://www.microsoft.com",
    # "https://www.github.com",
    # "https://www.glints.com",
    # "https://www.wix.com",
    # "https://www.square.com",
    # "https://www.stripe.com",
    # "https://www.codeigniter.com",
    # "https://www.laravel.com",
    # "https://www.cloudflare.com",
    # "https://www.heroku.com",
    # "https://www.digitalocean.com",
    # "https://www.shopify.com",
    # "https://www.wordpress.com",
    # "https://www.bitbucket.org",
    # 📱 Sosial & Komunikasi (10)
    # manual screenshot --
    # "https://www.facebook.com",
    # "https://www.twitter.com",
    # "https://www.instagram.com",
    # "https://www.tiktok.com",
    # "https://www.telegram.org",
    # "https://www.whatsapp.com",
    # "https://www.discord.com",
    # "https://www.linkedin.com",
    # "https://www.quora.com",
    # "https://www.snapchat.com",
    # 🧠 Portal Info Umum (10)
    # manual screenshot --
    # "https://www.wikipedia.org",
    # "https://www.google.com",
    # "https://www.stackexchange.com",
    # "https://www.stackoverflow.com",
    # "https://www.w3schools.com",
    # "https://www.geeksforgeeks.org",
    # "https://www.medium.com",
    # "https://www.dev.to",
    # "https://www.producthunt.com",
    # "https://www.hackernews.com",
    # 🏥 Kesehatan & Info Publik (10)
    # manual screenshot --
    # "https://www.halodoc.com",
    # "https://www.who.int",
    # "https://www.healthline.com",
    # "https://www.webmd.com",
    # "https://www.mayoclinic.org",
    # "https://www.cdc.gov",
    # "https://www.nih.gov",
    # "https://www.medicalnewstoday.com",
    # "https://www.drugs.com",
    # "https://www.health.gov",
    # 🧾 Review & Tech Info (10)
    # manual screenshot --
    # "https://www.gsmarena.com",
    # "https://www.notebookcheck.net",
    # "https://www.tomshardware.com",
    # "https://www.techradar.com",
    # "https://www.anandtech.com",
    # "https://www.pcmag.com",
    # "https://www.cnet.com",
    # "https://www.theverge.com",
    # "https://www.wired.com",
    # "https://www.engadget.com",
    # ✈️ Travel & Lifestyle (10)
    # manual screenshot --
    # "https://www.traveloka.com",
    # "https://www.agoda.com",
    # "https://www.booking.com",
    # "https://www.airbnb.com",
    # "https://www.tripadvisor.com",
    # "https://www.klook.com",
    # "https://www.tiket.com",
    # "https://www.trivago.com",
    # "https://www.expedia.com",
    # "https://www.indonesia.travel",
]


# TODO: seacrh 250 gambling sites from google search --- IGNORE ---
GAMBLING_SITES = [
    "https://garuda368jp.art",
    "https://gacor108b.xyz",
    "https://kuda898jepe.online",
    "https://zeus345win.online",
    "https://zeus138jp.org",
    "https://46-dt138.top",
    "https://77betsportsd.za.com",
    "https://basic4dside.store",
    "https://nona778.online",
    "https://multibet88cc.online",
    "https://depo77alter2.cfd",
    "https://kue68jpe.site",
    "https://rajamenang2.online",
    "https://osaka88mm.site",
    "https://duren777bb.site",
    "https://bintang11a.app",
    "https://maxwin717top.online",
    "https://maxwin303win.space",
    "https://toto17a.com",
    "https://bdslot88natal.com",
    "https://dewa878jp.online",
    "https://dewa90a.com",
    "https://vip855jp.online",
    "https://surga19jepe.online",
    "https://badak117ori.online",
    "https://hoki108b.org",
    "https://badak178kyc.site",
    "https://jago799.it.com",
    "https://badak178id.com",
    "https://lokasicjp.pro",
    "https://badak178bb.space",
    "https://playwin123jp.online",
    "https://badak178pgs.online",
    "https://slot337sportse.com",
    "https://produmacantoto.shop",
    "https://badak178gas.space",
    "https://slot-mjpvaxn0.kencana28.site",
    "https://buaya222vip.online",
    "https://buaya1388login.online",
    "https://linkmaxwin588.online",
    "https://naga15a.one",
    "https://linkgacor877.online",
    "https://sand77hoki.online",
    "https://raja222win.online",
    "https://slot8895.online",
    "https://hokislot95.site",
    "https://slot888pestawd100jt.online",
    "https://texas88gac0r.site",
    "https://ultislot88.net",
    "https://jawa178.site",
    "https://jackpot108jp.online",
    "https://mpo121vip.online",
    "https://toto12winjp.online",
    "https://ash88pro.site",
    "https://toto33maxwin.online",
    "https://www.idrhokim4.com",
    "https://vip.indohki77.store",
    "https://www.jalanninja2.store",
    "https://gosbb99.shop",
    "https://www.qqstar.co.uk",
    "https://togel108gacor.online",
    "https://ayam788.online",
    "https://homebet88gacor.world",
    "https://nustoto.com",
    "https://www.manggatoto.live",
    "https://akayatoto1.com",
    "https://aa02.kurniacuan.com",
    "https://hss4dc.com",
    "https://citibet88.cloud",
    "https://pphoki.com",
    "https://amp-gacorx500.net",
    "https://gacorx500cm.top",
    "https://hokicrut.site",
    "https://dealmaxwin.chat",
    "https://899sports.id",
    "https://mambawingacor.com",
    "https://hokicasto.com",
    "https://swotin.site",
    "https://www.nomor777.net",
    "https://king.ledak188-pit.com",
    "https://bandarmitosbet.online",
    "https://kudetabet98cottonjackpot.com",
    "https://zeusghacor.com",
    "https://zeusgacorslot.com",
    "https://www.zeusgacor99.net",
    "https://amp.igmaxwin.com",
    "https://villatogel1.site",
    "https://www.supertogel.id",
    "https://ayeaye.space",
    "https://ciamistoto8000.com",
    "https://8tburn.com",
    "https://kotatogel.com",
    "https://minitotobisa.com",
    "https://toto77-mobile.com",
    "https://www.youngtoto.com",
    "https://bebsebelas.com",
    "https://kuy4donline.top",
    "https://koipadang.com",
    "https://sigmatoto.com",
    "https://www.torpedo4d.com",
    "https://ubertogel.net",
    "https://jitutoto-amp.com",
    "https://danamitosbet.site",
    "https://ulartoto.com",
    "https://alidodo157.alitotogacor.net",
    "https://vw108jaya.online",
    "https://nagacuan-ms.site",
    "https://amp-mawartoto117.pages.dev",
    "https://triomacantoto.store",
    "https://raja787gac0r.site",
    "https://indobet11gac0r.site",
    "https://nagahoki69login2.site",
    "https://slot77asliresmi.online",
    "https://rajaslot80.com",
    "https://ledak311hoki.site",
    "https://cina2.xyz",
    "https://w33slotpromo.com",
    "https://ratuu23.sbs",
    "https://login.klikmenang.cc",
    "https://5.pentaslot.work",
    "https://judii14.xyz",
    "https://indokasino12.pialadunia.app",
    "https://11.kaikoslot.sbs",
    "https://gacorwon91.com",
    "https://16des.rusia777.sbs",
    "https://gabungdewa.com",
    "https://sv4.hokidewawin.com",
    "https://link13.koko88.website",
    "https://login17.bantengmerah.online",
    "https://login-10.sigacor88.ink",
    "https://login-3.jackpotdewa.cc",
    "https://join.kupontoto.io",
    "https://wongkito4dwin.com",
    "https://join.dewajitu.io",
    "https://coba.dewahk.io",
    "https://login.dewasgp.io",
    "https://ba.berubah.cc",
    "https://kp.pegashaha.cc",
    "https://gacor770.shop",
    "https://agen108d.online",
    "https://badak117link.online",
    "https://hoki108b.net",
    "https://agen108top.online",
    "https://mahjongjepe88.online",
    "https://mahjong333ok.site",
    "https://mahjongpg8808.online",
    "https://slot8808-alt2.online",
    "https://mahjongjp888.online",
    "https://maha333hoki.online",
    "https://maha222vip.online",
    "https://maha222pro.online",
    "https://raja373pro.online",
    "https://jackpot108dp.online",
    "https://jackpot108depo.online",
    "https://motowin77a.sa.com",
    "https://jackpot777.online",
    "https://daftarpanen88.top",
    "https://deposit909jp.online",
    "https://danatoto8808.online",
    "https://nanastoto898maxw1n.online",
    "https://lunatogel606vip.online",
    "https://lunatogel105.online",
    "https://dewajepe.pics",
    "https://mw303hokii.space",
    "https://rtp177maxwin.site",
    "https://gacor108b.online",
    "https://judol88win.site",
    "https://slotbd636.online",
    "https://garuda366vip.online",
    "https://garuda366win.site",
    "https://win135cuan.online",
    "https://petir108winb.online",
    "https://petir138jp.online",
    "https://cuan132.online",
    "https://sobet88mwin.top",
    "https://s1jphoki.site",
    "https://sbobet988slot.online",
    "https://sbobet988slot.xyz",
    "https://sbobet88parlay222.online",
    "https://slotgampang.net",
    "https://828betg.space",
    "https://cuan365jpprime.online",
    "https://joker365win.online",
    "https://joker368win.site",
    "https://betwin199.online",
    "https://betogel108id.online",
    "https://beton888vip.online",
    "https://serveragenplay88.life",
    "https://pastiwdd88.com",
    "https://wdbos212pro.online",
    "https://wd288asli.online",
    "https://slot888pastiwd.online",
    "https://slot888jekpot100jt.online",
    "https://queen99turbo3.sbs",
    "https://slot888gasbang.online",
    "https://panen88gokil.online",
    "https://win4d77.online",
    "https://depo77gac0r.site",
    "https://hoki17t0p.site",
    "https://hoki138entry.site",
    "https://bosku777best.com",
    "https://hoki138prize.com",
    "https://zeus432d.online",
    "https://zeus4dtopcer.net",
    "https://arena122play.online",
    "https://kaskustoto238win.online",
    "https://kaskustoto123jp.online",
    "https://kaskustoto889.org",
    "https://jaya389win.online",
    "https://cair112win.online",
    "https://situsmega855.site",
    "https://situsgacor777vip.site",
    "https://situshoki606.online",
    "https://nagaplay333.online",
    "https://planetwin855.online",
    "https://spinbet99d.online",
    "https://super345win.online",
    "https://jitu268togel.online",
    "https://musang171bet.online",
    "https://musangsl0t.online",
    "https://calo288pro.site",
    "https://musang178z.space",
    "https://musang288wdregist.site",
    "https://dewa138menangnih.com",
    "https://dewa138hf.com",
    "https://poker888jp.online",
    "https://poker168apk.online",
    "https://sengtotogel.online",
    "https://sengtotogelvip.online",
    "https://idrslot39.com",
    "https://citibet88b.fit",
    "https://gaskan9.xyz",
    "https://sengtoto2d.space",
    "https://vip555gcr.online",
    "https://surga11wn.site",
    "https://lotus389.online",
    "https://linktergacor687.online",
    "https://linksl0trans4t.world",
    "https://mawartop88.site",
    "https://mawartotogel858.online",
    "https://salaktoto99win.site",
    "https://linkjepe138m.com",
    "https://www.mpo76.net",
    "https://dewi173win.online",
    "https://www.dewagacor99.org",
    "https://king.ayo788-pit.com",
    "https://komodo677.site",
    "https://banteng778.online",
    "https://alexis128maxwin.site",
    "https://alexis313toto.online",
]
